name: 'very test'

on: push

jobs:
  github:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: setup
        run: |
          sudo apt update -y 
          sudo apt install -y g++

      - name: compile
        run: |
          g++ superbsoftware.cpp -o superbsoftware

      - name: run and format output
        run: |
          ./superbsoftware > raw_output.txt
          python3 format.py

      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'customSmallerIsBetter'
          auto-push: true
          output-file-path: out.json
          fail-on-alert: true
          alert-comment-cc-users: '@okBrian'
          alert-threshold: '200%'
          comment-on-alert: true
          gh-repository: 'github.com/okBrian/cont-integration-stats'
          github-token: ${{ secrets.TOKEN }}
